project_id = "ygweyscocelwjcqinkth"

[api]
enabled = true
[auth]
enabled = true
[realtime]
enabled = true

[[functions]]
[functions.instagram-auth]
verify_jwt = true

[[functions]]
[functions.instagram-webhook]
verify_jwt = false