project_id = "ygweyscocelwjcqinkth"

[api]
enabled = true
[auth]
enabled = true
[realtime]
enabled = true

[[functions]]
name = "instagram-auth"
verify_jwt = true

[[functions]]
name = "instagram-webhook"
verify_jwt = false