
project_id = "ygweyscocelwjcqinkth"

[api]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.instagram-auth]
verify_jwt = true

[functions.instagram-webhook]
verify_jwt = false

[functions.get-instagram-client-id]
verify_jwt = false

[functions.instagram-analyze]
verify_jwt = false

[functions.instagram-scrape]
verify_jwt = false

[functions.deepseek-chat]
verify_jwt = false

[functions.tiktok-auth]
verify_jwt = true

[functions.tiktok-verify]
verify_jwt = false

[functions.gemini-image]
verify_jwt = false

[functions.vertex-image]
verify_jwt = false

[functions.analyze-content]
verify_jwt = false

[functions.video-analyze]
verify_jwt = false

[functions.replicate-image]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false

[functions.celebrity-aware-chat]
verify_jwt = false
